name: Deploy Dev

on:
  push:
    branches: ["develop"]

concurrency:
  group: deploy-dev
  cancel-in-progress: true

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ steps.deploy.outputs.url }}
    env:
      WORKDIR: "."
      NEXT_TELEMETRY_DISABLED: "1"
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Build (prebuild)
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Preview/Staging)
        id: deploy
        run: |
          URL=$(vercel deploy --prebuilt \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --project ${{ secrets.VERCEL_PROJECT_ID_DEV }} \
            --scope ${{ secrets.VERCEL_ORG_ID }})
          echo "url=$URL" >> $GITHUB_OUTPUT
